### ISSUE TITLE
Not Yet Reviewed

### ISSUE THREAD

**Issue by arranf** [limejump/hermit#1]
Hey guys this code hasn't reviewed. Before it gets pushed to prod can you take some time to scan your eyes over it?

**Comment by willgraham0** [comment]
I like the idea of using DTOs a lot, although I'm not sure I follow how you intend to use the pattern in this case, particularly when writing logs. Would like to learn though!

**Comment by arranf** [comment]
I'm going to close this issue now it's open sourced!
